import { ProProfile, Product } from '../types'

export const MOCK_PROS: ProProfile[] = [
  {
    id: 'pro-1',
    userId: 'u1',
    name: 'Sophie Martin',
    specialties: ['COIFFURE'],
    bio: 'Coiffeuse passionnée avec 10 ans d\'expérience. Spécialisée en colorations végétales et coupes tendance. Je prends soin de chaque cheveu comme s\'il était unique.',
    city: 'Paris',
    photoUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&h=400&fit=crop',
    siret: '73282932000074',
    siretVerified: true,
    isActive: true,
    rating: 4.8,
    services: [
      { id: 's1', proId: 'pro-1', name: 'Coupe femme', price: 45, durationMinutes: 45 },
      { id: 's2', proId: 'pro-1', name: 'Coloration complète', price: 85, durationMinutes: 90 },
      { id: 's3', proId: 'pro-1', name: 'Balayage', price: 110, durationMinutes: 120 },
      { id: 's4', proId: 'pro-1', name: 'Brushing', price: 30, durationMinutes: 30 },
    ],
    availabilities: [
      { id: 'a1', proId: 'pro-1', dayOfWeek: 0, startTime: '09:00', endTime: '18:00' },
      { id: 'a2', proId: 'pro-1', dayOfWeek: 1, startTime: '09:00', endTime: '18:00' },
      { id: 'a3', proId: 'pro-1', dayOfWeek: 2, startTime: '09:00', endTime: '18:00' },
      { id: 'a4', proId: 'pro-1', dayOfWeek: 3, startTime: '09:00', endTime: '18:00' },
      { id: 'a5', proId: 'pro-1', dayOfWeek: 4, startTime: '09:00', endTime: '17:00' },
    ],
    products: [
      {
        id: 'p1', proId: 'pro-1', name: 'Shampoing éclat couleur', category: 'SOIN',
        price: 18, stock: 20, isActive: true,
        description: 'Protège et sublime les colorations',
        photoUrl: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=300&h=300&fit=crop',
      },
    ],
  },
  {
    id: 'pro-2',
    userId: 'u2',
    name: 'Camille Dubois',
    specialties: ['ESTHETIQUE', 'MASSAGE'],
    bio: 'Esthéticienne diplomée et masseuse bien-être. Je propose des soins du visage personnalisés et des massages relaxants dans un cadre apaisant.',
    city: 'Lyon',
    photoUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400&h=400&fit=crop',
    siret: '80263460900019',
    siretVerified: true,
    isActive: true,
    rating: 4.9,
    services: [
      { id: 's5', proId: 'pro-2', name: 'Soin visage hydratant', price: 65, durationMinutes: 60 },
      { id: 's6', proId: 'pro-2', name: 'Épilation jambes complètes', price: 40, durationMinutes: 45 },
      { id: 's7', proId: 'pro-2', name: 'Massage relaxant', price: 70, durationMinutes: 60 },
      { id: 's8', proId: 'pro-2', name: 'Massage aux pierres chaudes', price: 90, durationMinutes: 75 },
    ],
    availabilities: [
      { id: 'a6', proId: 'pro-2', dayOfWeek: 1, startTime: '10:00', endTime: '19:00' },
      { id: 'a7', proId: 'pro-2', dayOfWeek: 2, startTime: '10:00', endTime: '19:00' },
    ],
    products: [
      {
        id: 'p2', proId: 'pro-2', name: 'Huile de massage relaxante', category: 'SOIN',
        price: 22, stock: 12, isActive: true,
        description: 'Mélange d\'huiles essentielles apaisantes',
        photoUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&h=300&fit=crop',
      },
    ],
  },
  {
    id: 'pro-3',
    userId: 'u3',
    name: 'Léa Fontaine',
    specialties: ['NAIL_ART'],
    bio: 'Nail artist créative, spécialisée en gel, résine et nail art personnalisé. Chaque ongle est une œuvre d\'art ! Tarifs transparents, résultats impeccables.',
    city: 'Bordeaux',
    photoUrl: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&h=400&fit=crop',
    siret: '51234567800017',
    siretVerified: true,
    isActive: true,
    rating: 5.0,
    services: [
      { id: 's9', proId: 'pro-3', name: 'Pose gel couleur', price: 55, durationMinutes: 60 },
      { id: 's10', proId: 'pro-3', name: 'Nail art (par ongle)', price: 5, durationMinutes: 10 },
      { id: 's11', proId: 'pro-3', name: 'Remplissage gel', price: 40, durationMinutes: 45 },
      { id: 's12', proId: 'pro-3', name: 'Semi-permanent', price: 35, durationMinutes: 45 },
    ],
    availabilities: [
      { id: 'a8', proId: 'pro-3', dayOfWeek: 2, startTime: '10:00', endTime: '18:00' },
      { id: 'a9', proId: 'pro-3', dayOfWeek: 5, startTime: '09:00', endTime: '15:00' },
    ],
    products: [],
  },
  {
    id: 'pro-4',
    userId: 'u4',
    name: 'Marie Leclerc',
    specialties: ['MAQUILLAGE'],
    bio: 'Maquilleuse professionnelle pour mariages, shootings et événements. Je sublime votre beauté naturelle avec des techniques douces et des produits haut de gamme.',
    city: 'Paris',
    photoUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop',
    siret: '40483304800023',
    siretVerified: true,
    isActive: true,
    rating: 4.7,
    services: [
      { id: 's13', proId: 'pro-4', name: 'Maquillage mariée', price: 150, durationMinutes: 90 },
      { id: 's14', proId: 'pro-4', name: 'Maquillage soirée', price: 80, durationMinutes: 60 },
      { id: 's15', proId: 'pro-4', name: 'Cours de maquillage', price: 95, durationMinutes: 90 },
      { id: 's16', proId: 'pro-4', name: 'Maquillage naturel', price: 60, durationMinutes: 45 },
    ],
    availabilities: [
      { id: 'a10', proId: 'pro-4', dayOfWeek: 5, startTime: '08:00', endTime: '20:00' },
      { id: 'a11', proId: 'pro-4', dayOfWeek: 6, startTime: '08:00', endTime: '20:00' },
    ],
    products: [
      {
        id: 'p3', proId: 'pro-4', name: 'Palette fards à paupières', category: 'MAQUILLAGE',
        price: 55, stock: 4, isActive: true,
        description: '12 teintes nude et smoky',
        photoUrl: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=300&h=300&fit=crop',
      },
    ],
  },
  {
    id: 'pro-5',
    userId: 'u5',
    name: 'Julia Renard',
    specialties: ['MASSAGE'],
    bio: 'Masseuse bien-être certifiée en massages suédois, balinais et drainage lymphatique. Chaque séance est une parenthèse de détente absolue.',
    city: 'Marseille',
    photoUrl: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&h=400&fit=crop',
    siret: '61234567800011',
    siretVerified: true,
    isActive: true,
    rating: 4.6,
    services: [
      { id: 's17', proId: 'pro-5', name: 'Massage suédois 1h', price: 75, durationMinutes: 60 },
      { id: 's18', proId: 'pro-5', name: 'Massage balinais', price: 85, durationMinutes: 75 },
      { id: 's19', proId: 'pro-5', name: 'Drainage lymphatique', price: 90, durationMinutes: 60 },
    ],
    availabilities: [
      { id: 'a12', proId: 'pro-5', dayOfWeek: 0, startTime: '09:00', endTime: '17:00' },
      { id: 'a13', proId: 'pro-5', dayOfWeek: 3, startTime: '09:00', endTime: '17:00' },
    ],
    products: [
      {
        id: 'p4', proId: 'pro-5', name: 'Huile de coco bio', category: 'SOIN',
        price: 14, stock: 25, isActive: true,
        description: 'Idéale pour l\'hydratation et le massage',
        photoUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=300&h=300&fit=crop',
      },
    ],
  },
  {
    id: 'pro-6',
    userId: 'u6',
    name: 'Inès Benali',
    specialties: ['COIFFURE', 'ESTHETIQUE'],
    bio: 'Experte en beauté globale : coiffure afro et texturée, soins visage et corps. Beauté inclusive, tous types de cheveux et de peaux. Bienvenue à toutes !',
    city: 'Toulouse',
    photoUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=400&fit=crop',
    siret: '71234567800015',
    siretVerified: true,
    isActive: true,
    rating: 4.9,
    services: [
      { id: 's20', proId: 'pro-6', name: 'Coiffure afro (nattes)', price: 80, durationMinutes: 120 },
      { id: 's21', proId: 'pro-6', name: 'Soin cheveux bouclés', price: 55, durationMinutes: 60 },
      { id: 's22', proId: 'pro-6', name: 'Soin visage éclat', price: 60, durationMinutes: 50 },
    ],
    availabilities: [
      { id: 'a14', proId: 'pro-6', dayOfWeek: 1, startTime: '09:00', endTime: '18:00' },
      { id: 'a15', proId: 'pro-6', dayOfWeek: 4, startTime: '09:00', endTime: '18:00' },
      { id: 'a16', proId: 'pro-6', dayOfWeek: 6, startTime: '09:00', endTime: '15:00' },
    ],
    products: [],
  },
]

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1', proId: 'pro-1', name: 'Shampoing éclat couleur', category: 'SOIN',
    price: 18, stock: 20, isActive: true,
    description: 'Protège et sublime les colorations. Sans sulfates.',
    photoUrl: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=300&h=300&fit=crop',
    pro: { name: 'Sophie Martin', city: 'Paris' },
  },
  {
    id: 'p2', proId: 'pro-2', name: 'Huile de massage relaxante', category: 'SOIN',
    price: 22, stock: 12, isActive: true,
    description: 'Mélange d\'huiles essentielles apaisantes — lavande, camomille.',
    photoUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&h=300&fit=crop',
    pro: { name: 'Camille Dubois', city: 'Lyon' },
  },
  {
    id: 'p3', proId: 'pro-4', name: 'Palette fards à paupières', category: 'MAQUILLAGE',
    price: 55, stock: 4, isActive: true,
    description: '12 teintes nude et smoky, longue tenue, sans paraben.',
    photoUrl: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=300&h=300&fit=crop',
    pro: { name: 'Marie Leclerc', city: 'Paris' },
  },
  {
    id: 'p4', proId: 'pro-5', name: 'Huile de coco bio', category: 'SOIN',
    price: 14, stock: 25, isActive: true,
    description: 'Pressée à froid, certifiée bio. Idéale pour l\'hydratation et le massage.',
    photoUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=300&h=300&fit=crop',
    pro: { name: 'Julia Renard', city: 'Marseille' },
  },
  {
    id: 'p5', proId: 'pro-4', name: 'Fond de teint longue tenue', category: 'MAQUILLAGE',
    price: 42, stock: 6, isActive: true,
    description: 'Tenue 24h, fini naturel, 30 teintes disponibles.',
    photoUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=300&h=300&fit=crop',
    pro: { name: 'Marie Leclerc', city: 'Paris' },
  },
  {
    id: 'p6', proId: 'pro-2', name: 'Crème visage hydratante SPF30', category: 'SOIN',
    price: 35, stock: 8, isActive: true,
    description: 'Protection solaire et hydratation quotidienne. Texture légère.',
    photoUrl: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=300&h=300&fit=crop',
    pro: { name: 'Camille Dubois', city: 'Lyon' },
  },
]
